/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gst.shuf;

import edu.wpi.first.shuffleboard.api.plugin.Description;
import edu.wpi.first.shuffleboard.api.plugin.Plugin;
import edu.wpi.first.shuffleboard.api.widget.ComponentType;
import edu.wpi.first.shuffleboard.api.widget.WidgetType;
import org.freedesktop.gstreamer.Version;
import org.freedesktop.gstreamer.Gst;

import java.util.List;

@Description(group = "gst", name="shuf", version="1.0.0", summary="hopefully gstreamer shuffleboard thingy")
public class ShufPlugin extends Plugin {
    public ShufPlugin() {
        // I think this works
        GstreamerUtils.configurePaths();
        Gst.init(Version.BASELINE, "gst-shuf");
    }

    @Override
    public List<ComponentType> getComponents() {
        return List.of(WidgetType.forAnnotatedWidget(GstWidget.class));
    }
}
